// LLMOps Research Assistant — Azure Infrastructure
// Generated by infra/azure_deploy.py
// Deploy: az deployment group create --resource-group llmops-rg --template-file main.bicep

param location string = 'eastus'
param acrName string = 'llmopsacr'
param acaEnvironmentName string = 'llmops-env'
param apiAppName string = 'llmops-api'
param workerAppName string = 'llmops-worker'
param amlWorkspaceName string = 'llmops-aml'
param logAnalyticsName string = 'llmops-logs'
param appInsightsName string = 'llmops-insights'

// Log Analytics Workspace
resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {
  name: logAnalyticsName
  location: location
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: 30
  }
}

// Application Insights
resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalytics.id
  }
}

// Azure Container Registry
resource acr 'Microsoft.ContainerRegistry/registries@2023-01-01-preview' = {
  name: acrName
  location: location
  sku: { name: 'Standard' }
  properties: {
    adminUserEnabled: false
    anonymousPullEnabled: false
  }
}

// Container Apps Managed Environment
resource acaEnv 'Microsoft.App/managedEnvironments@2023-05-01' = {
  name: acaEnvironmentName
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
    daprAIInstrumentationKey: appInsights.properties.InstrumentationKey
  }
}

// API Container App — external HTTPS ingress, HTTP KEDA autoscaling
resource apiApp 'Microsoft.App/containerApps@2023-05-01' = {
  name: apiAppName
  location: location
  identity: { type: 'SystemAssigned' }
  properties: {
    managedEnvironmentId: acaEnv.id
    configuration: {
      ingress: {
        external: true
        targetPort: 8000
        transport: 'http'
        allowInsecure: false
      }
      registries: [{
        server: acr.properties.loginServer
        identity: 'system'
      }]
    }
    template: {
      containers: [{
        name: 'api'
        image: '${acr.properties.loginServer}/llmops-api:latest'
        resources: {
          cpu: json('1.0')
          memory: '2Gi'
        }
        probes: [{
          type: 'Liveness'
          httpGet: { path: '/health', port: 8000 }
          initialDelaySeconds: 10
          periodSeconds: 30
        }]
      }]
      scale: {
        minReplicas: 1
        maxReplicas: 10
        rules: [{
          name: 'http-scaling'
          http: { metadata: { concurrentRequests: '50' } }
        }]
      }
    }
  }
}

// Worker Container App — scale-to-zero, Redis KEDA trigger
resource workerApp 'Microsoft.App/containerApps@2023-05-01' = {
  name: workerAppName
  location: location
  identity: { type: 'SystemAssigned' }
  properties: {
    managedEnvironmentId: acaEnv.id
    configuration: {
      registries: [{
        server: acr.properties.loginServer
        identity: 'system'
      }]
    }
    template: {
      containers: [{
        name: 'worker'
        image: '${acr.properties.loginServer}/llmops-worker:latest'
        resources: {
          cpu: json('2.0')
          memory: '4Gi'
        }
        command: ['celery', '-A', 'ingestion.batch_processor', 'worker', '--loglevel=info']
      }]
      scale: {
        minReplicas: 0
        maxReplicas: 10
      }
    }
  }
}

// Azure ML Workspace
resource amlWorkspace 'Microsoft.MachineLearningServices/workspaces@2023-06-01-preview' = {
  name: amlWorkspaceName
  location: location
  identity: { type: 'SystemAssigned' }
  properties: {
    applicationInsights: appInsights.id
    containerRegistry: acr.id
  }
}

output apiUrl string = 'https://${apiApp.properties.configuration.ingress.fqdn}'
output acrLoginServer string = acr.properties.loginServer
output amlWorkspaceId string = amlWorkspace.id
output appInsightsConnectionString string = appInsights.properties.ConnectionString
